version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
